### ISSUE TITLE
build for aarch64 is missing in the latest release

### ISSUE THREAD

**Issue by janrinze** [FPGAwars/tools-system#5]
build for aarch64 is missing in the latest release.

**Comment by Obijuan** [comment]
Yes. The tools-system is now considered deprecated. The latest apio version (0.7.6) does not use it anymore.  The new system tools are located in the toos-oss-cad-suite package. I am working on it. Currently the packages are not generated for the aarch64 but they will. 

I will close this issue. Please, add another issue on the [tools-oss-cad-suite](https://github.com/FPGAwars/tools-oss-cad-suite/wiki). Thanks for your help
